spring.application.name=Module-15-Docker

spring.datasource.url=jdbc:postgresql://product-db:5432/product-db
spring.datasource.username=soham
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
